openapi: 3.0.0
info:
  title: Supplya API Documentation
  description: Supplya API
  contact: {}
  version: "1.0"
servers:
  - url: http://localhost:3000/api/v1
    description: "Local server"
  - url: https://prodsupplya.azurewebsites.net/api/v1
    description: "Test server"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /products:
    post:
      tags:
        - Product
      summary: Create Product
      description: Create new product for the admin or owner
      operationId: CreateProduct
      parameters: []
      requestBody:
        content:
          application/json:
            encoding: {}
            schema:
              required:
                - name
                - description
                - unit_price
                - discounted_price
                - quantity
                - image
                - category
                - sku
                - moq
                - status
              type: object
              properties:
                product:
                  type: string
                unit_price:
                  type: integer
                  format: int32
                  example: 32000
                discounted_price:
                  type: integer
                  format: int32
                  example: 30000
                name:
                  type: string
                  example: Rice
                description:
                  type: string
                  example: Bag of rice
                quantity:
                  type: integer
                  format: int32
                  example: 100
                sku:
                  type: string
                  example: 19802UE
                moq:
                  type: int32
                  example: 5
                status:
                  type: string
                  example: inStock
                category:
                  type: string
                  example: Food
        required: false
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    get:
      tags:
        - Product
      summary: Get All Products
      description: Get all products
      operationId: GetAllProducts
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /products/submit:
    post:
      tags:
        - Product
      summary: Submit Product
      description: Submit new product for the admin to approve
      operationId: SubmitProduct
      parameters: []
      requestBody:
        content:
          application/json:
            encoding: {}
            schema:
              required:
                - name
                - description
                - unit_price
                - discounted_price
                - quantity
                - image
                - category
                - sku
                - moq
                - status
              type: object
              properties:
                product:
                  type: string
                unit_price:
                  type: integer
                  format: int32
                  example: 32000
                discounted_price:
                  type: integer
                  format: int32
                  example: 30000
                name:
                  type: string
                  example: Rice
                description:
                  type: string
                  example: Bag of rice
                quantity:
                  type: integer
                  format: int32
                  example: 100
                sku:
                  type: string
                  example: 19802UE
                moq:
                  type: int32
                  example: 5
                status:
                  type: string
                  example: inStock
                category:
                  type: string
                  example: Food
        required: false
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - BearerAuth: []
  /products/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The product ID
    delete:
      tags:
        - Product
      summary: Delete Product
      description: Delete a product
      operationId: DeleteProduct
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - BearerAuth: []
    get:
      tags:
        - Product
      summary: Get Single Product
      description: Get single product
      operationId: GetSingleProduct
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      
    patch:
      tags:
        - Product
      summary: Edit Product
      description: Edit a product
      operationId: EditProduct
      parameters: []
      requestBody:
        content:
          application/json:
            encoding: {}
            schema:
              required:
                - price
              type: object
              properties:
                price:
                  type: integer
                  format: int32
                  example: 45000
        required: false
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false

  /products/flashsale:
    get:
      tags:
        - Product
      summary: Get Flashsale Products
      description: Get products listed on flashsale
      operationId: GetFlashsaleProducts
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    
  /products/deals:
    get:
      tags:
        - Product
      summary: Get Discounted Products
      description: Get products with discount
      operationId: GetDiscountedProducts
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  
  /inventory:
    get:
      tags:
        - Inventory
      summary: Get all inventory list
      description: Get all inventory lists
      operationId: Getallinventorylist
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    post:
      tags:
        - Inventory
      summary: Create inventory list
      description: Create new inventory list for only warehouse manager
      operationId: Createinventorylist
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/CreateinventorylistRequest"
                - example:
                    inventoryItems:
                      - productId: 63712313cecef52a241893ea
                        quantity: 30
                      - productId: 6371232dcecef52a241893ec
                        quantity: 25
                      - productId: 637122e5cecef52a241893e8
                        quantity: 60
                      - productId: 637122b0cecef52a241893e6
                        quantity: 50
                      - productId: 63712286cecef52a241893e4
                        quantity: 10
                      - productId: 6371226fcecef52a241893e2
                        quantity: 73
            example:
              inventoryItems:
                - productId: 63712313cecef52a241893ea
                  quantity: 30
                - productId: 6371232dcecef52a241893ec
                  quantity: 25
                - productId: 637122e5cecef52a241893e8
                  quantity: 60
                - productId: 637122b0cecef52a241893e6
                  quantity: 50
                - productId: 63712286cecef52a241893e4
                  quantity: 10
                - productId: 6371226fcecef52a241893e2
                  quantity: 73
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /inventory/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The inventory ID
    patch:
      tags:
        - Inventory
      summary: Edit inventory list
      description: Make edits to declined inventory lists for warehouse manager
      operationId: Editinventorylist
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/EditinventorylistRequest"
                - example:
                    inventoryItems:
                      - productId: 63712313cecef52a241893ea
                        quantity: 30
                      - productId: 6371232dcecef52a241893ec
                        quantity: 15
                      - productId: 637122e5cecef52a241893e8
                        quantity: 12
                      - productId: 637122b0cecef52a241893e6
                        quantity: 5
                      - productId: 63712286cecef52a241893e4
                        quantity: 9
                      - productId: 6371226fcecef52a241893e2
                        quantity: 14
            example:
              inventoryItems:
                - productId: 63712313cecef52a241893ea
                  quantity: 30
                - productId: 6371232dcecef52a241893ec
                  quantity: 15
                - productId: 637122e5cecef52a241893e8
                  quantity: 12
                - productId: 637122b0cecef52a241893e6
                  quantity: 5
                - productId: 63712286cecef52a241893e4
                  quantity: 9
                - productId: 6371226fcecef52a241893e2
                  quantity: 14
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    get:
      tags:
        - Inventory
      summary: Get Single Inventory List
      description: Get single inventory lists by Id for all except cashier
      operationId: GetSingleInventoryList
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /inventory/status/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The inventory ID
    patch:
      tags:
        - Inventory
      summary: Change List Status
      description: Approve or Decline inventory lists, by passing approve or decline in the id parameter for owner and admin
      operationId: ChangeListStatus
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/ChangeListStatusRequest"
                - example:
                    status: declined
            example:
              status: declined
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    get:
      tags:
        - Inventory
      summary: Get inventory by status
      description: Gets inventory lists by status according to what parameter you pass in(eg verified,declined or pending) in id  parameter for owner and admin
      operationId: GetinventorybyStatus
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /inventory/branchStatus/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The inventory ID
    get:
      tags:
        - Inventory
      summary: Get list by branch
      description: Gets inventory list by status passed in and by users branch
      operationId: Getlistbybranch
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /sale:
    post:
      tags:
        - Sales
      summary: Make a new sale
      description: Make a sale for cashier only
      operationId: Makeanewsale
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/MakeanewsaleRequest"
                - example:
                    saleList:
                      - productId: 63712313cecef52a241893ea
                        quantity: 2
                      - productId: 6371232dcecef52a241893ec
                        quantity: 5
                      - productId: 637122b0cecef52a241893e6
                        quantity: 5
                    method: bank transfer
            example:
              saleList:
                - productId: 63712313cecef52a241893ea
                  quantity: 2
                - productId: 6371232dcecef52a241893ec
                  quantity: 5
                - productId: 637122b0cecef52a241893e6
                  quantity: 5
              method: bank transfer
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    get:
      tags:
        - Sales
      summary: Get all Sales
      description: Get all sales for all
      operationId: GetallSales
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /sale/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The sale ID
    get:
      tags:
        - Sales
      summary: Get single sale
      description: Get single sales for all
      operationId: Getsinglesale
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /sale/daily/today:
    get:
      tags:
        - Sales
      summary: Get Daily Sales
      description: Get daily sales for all
      operationId: GetDailySales
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /sale/branch/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The inventory ID
    get:
      tags:
        - Sales
      summary: Get Sales by branch
      description: Get sales by branch by passing values like benin, lagos or abuja in id pararmeter for all but cashier and warehouse-manager
      operationId: GetSalesbybranch
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /auth/sign-up:
    post:
      tags:
        - Auth
      summary: Sign up
      description: Sign up as a customer or vendor
      operationId: SignUp
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/SignUpRequest"
                - example:
                    name: Osama Okunbo
                    role: vendor
                    password: "123456789"
                    uniqueKey: biz7634@web32
                    email: info.drosama@gmail.com
            example:
              name: Osama Okunbo
              role: owner
              password: "123456789"
              uniqueKey: biz7634@web32
              email: info.drosama@gmail.com
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
      servers:
        - url: https://odd-rose-turkey-wear.cyclic.app/api/v1
          variables: {}
  /registerUser:
    post:
      tags:
        - Auth
      summary: Register User
      description: Register other users besides like the admin, cashier and warehouse-manager
      operationId: RegisterUser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/RegisterUserRequest"
                - example:
                    name: Umoru Emmanuel`
                    role: ADMIN
                    password: "123456789"
                    email: umoru@gmail.com
            example:
              name: Umoru Emmanuel`
              role: ADMIN
              password: "123456789"
              email: umoru@gmail.com
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Login Users with Email and Password
      operationId: Login
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/LoginRequest"
                - example:
                    password: "1234$Vendor"
                    email: osuchukwudavid@gmail.com
            example:
              password: "1234$Vendor"
              email: osuchukwudavid@gmail.com
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /users:
    get:
      tags:
        - User
      summary: Get Users
      description: Get all users for the super admin
      operationId: GetUsers
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /users/orders:
    get:
      tags:
        - User
      summary: Get Users Orders
      description: Get all users orders
      operationId: GetUsersOrders
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - BearerAuth: []
  /changePassword/{id}:
  
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The user ID
    patch:
      tags:
        - User
      summary: Change Password
      description: Change user password to be carried out by the super admin
      operationId: ChangePassword
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/ChangePasswordRequest"
                - example:
                    password: osama2016
            example:
              password: osama2016
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
            security:
              - BearerAuth: []
  /deleteUser/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The inventory ID
    delete:
      tags:
        - User
      summary: Delete User
      description: Delete a user for the super admin
      operationId: DeleteUser
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
            security:
              - BearerAuth: []
components:
  schemas:
    RegisterOwnerRequest:
      title: RegisterOwnerRequest
      required:
        - name
        - role
        - password
        - uniqueKey
        - email
      type: object
      properties:
        name:
          type: string
        role:
          type: string
        password:
          type: string
        uniqueKey:
          type: string
        email:
          type: string
      example:
        name: Osama Okunbo
        role: owner
        password: "123456789"
        uniqueKey: biz7634@web32
        email: info.drosama@gmail.com
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - name
        - role
        - password
        - email
      type: object
      properties:
        name:
          type: string
        role:
          type: string
        password:
          type: string
        email:
          type: string
      example:
        name: Umoru Emmanuel`
        role: ADMIN
        password: "123456789"
        email: umoru@gmail.com
    ChangePasswordRequest:
      title: ChangePasswordRequest
      required:
        - password
      type: object
      properties:
        password:
          type: string
      example:
        password: osama2016
    LoginRequest:
      title: LoginRequest
      required:
        - password
        - email
      type: object
      properties:
        password:
          type: string
        email:
          type: string
      example:
        password: "123456789"
        email: cashier1@gmail.com
    CreateinventorylistRequest:
      title: CreateinventorylistRequest
      required:
        - inventoryItems
      type: object
      properties:
        inventoryItems:
          type: array
          items:
            $ref: "#/components/schemas/InventoryItem"
          description: ""
      example:
        inventoryItems:
          - productId: 63712313cecef52a241893ea
            quantity: 30
          - productId: 6371232dcecef52a241893ec
            quantity: 25
          - productId: 637122e5cecef52a241893e8
            quantity: 60
          - productId: 637122b0cecef52a241893e6
            quantity: 50
          - productId: 63712286cecef52a241893e4
            quantity: 10
          - productId: 6371226fcecef52a241893e2
            quantity: 73
    InventoryItem:
      title: InventoryItem
      required:
        - productId
        - quantity
      type: object
      properties:
        productId:
          type: string
        quantity:
          type: integer
          format: int32
      example:
        productId: 63712313cecef52a241893ea
        quantity: 30
    EditinventorylistRequest:
      title: EditinventorylistRequest
      required:
        - inventoryItems
      type: object
      properties:
        inventoryItems:
          type: array
          items:
            $ref: "#/components/schemas/InventoryItem"
          description: ""
      example:
        inventoryItems:
          - productId: 63712313cecef52a241893ea
            quantity: 30
          - productId: 6371232dcecef52a241893ec
            quantity: 15
          - productId: 637122e5cecef52a241893e8
            quantity: 12
          - productId: 637122b0cecef52a241893e6
            quantity: 5
          - productId: 63712286cecef52a241893e4
            quantity: 9
          - productId: 6371226fcecef52a241893e2
            quantity: 14
    ChangeListStatusRequest:
      title: ChangeListStatusRequest
      required:
        - status
      type: object
      properties:
        status:
          type: string
      example:
        status: declined
    MakeanewsaleRequest:
      title: MakeanewsaleRequest
      required:
        - saleList
        - method
      type: object
      properties:
        saleList:
          type: array
          items:
            $ref: "#/components/schemas/SaleList"
          description: ""
        method:
          type: string
      example:
        saleList:
          - productId: 63712313cecef52a241893ea
            quantity: 2
          - productId: 6371232dcecef52a241893ec
            quantity: 5
          - productId: 637122b0cecef52a241893e6
            quantity: 5
        method: bank transfer
    SaleList:
      title: SaleList
      required:
        - productId
        - quantity
      type: object
      properties:
        productId:
          type: string
        quantity:
          type: integer
          format: int32
      example:
        productId: 63712313cecef52a241893ea
        quantity: 2
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
  - httpBearer: []
tags:
  - name: Product
  - name: Inventory
  - name: Sales
  - name: Auth
    description: ""
  - name: User
    description: ""
